FROM node:22-alpine AS base
WORKDIR /app/frontend
COPY package*.json ./
RUN npm install

FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

# FROM base AS build
# RUN npm run build

FROM base AS prod
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]