# Frontend Dockerfile
FROM node:22-alpine

WORKDIR /app

# Install frontend dependencies
COPY package*.json ./
RUN npm install

# Copy frontend source code
COPY . ./frontend

# Expose the port for frontend
EXPOSE 5173

# Command to start the frontend
CMD ["npm", "run", "dev"]