# Base stage for installing dependencies
FROM node:22-alpine AS base
WORKDIR /app/frontend
COPY package*.json ./
RUN npm install

# Development stage
FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

# Build stage for production build
FROM base AS build
COPY . .
RUN npm run build

# Production stage for serving the built app
FROM node:22-alpine AS prod
WORKDIR /app/frontend
COPY --from=build /app/frontend/build ./build
EXPOSE 3000
CMD ["node", "build/index.js"]