# Dockerfile.frontend
FROM node:22-alpine

WORKDIR /app

# Install dependencies for frontend
COPY frontend/package*.json ./
RUN npm install

# Copy the frontend source code
COPY frontend/ ./

# Expose the frontend port
EXPOSE 5173

# Command to start the frontend
CMD ["npm", "run", "dev"]
