# Dockerfile.backend
FROM node:22-alpine

WORKDIR /app

# Install dependencies for backend
COPY backend/package*.json ./
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the backend source code
COPY backend/ ./

# Expose the backend port
EXPOSE 3000

# Command to start the backend
CMD ["nodemon", "index.js"]
