FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

# Copy the source code
COPY . .

# Expose the port the backend runs on
EXPOSE 3001

# Command to start the backend
CMD ["nodemon", "index.js"]