FROM node:22-alpine AS base
WORKDIR /app/backend
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

FROM base AS dev
EXPOSE 3000
CMD ["npm", "run", "start"]

# FROM base AS build
# RUN npm run build

FROM base AS prod
COPY . .
EXPOSE 3000
ENV ORIGIN=https://egp-broker.endeavour.cs.vt.edu
CMD ["npm", "run", "start"]
