FROM node:22-alpine as base
WORKDIR /app/backend
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

FROM base AS dev
EXPOSE 3000
CMD ["npm", "run", "start"]

# FROM base AS build
# RUN npm run build

FROM base as prod
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start"]
