# Backend Dockerfile
FROM node:22-alpine

WORKDIR /app/backend

# Install backend dependencies
COPY package*.json ./
RUN npm install

# Copy backend source code
COPY . ./

# Install nodemon for development
RUN npm install -g nodemon

# Expose the port for backend
EXPOSE 3000

# Command to start the backend
CMD ["nodemon", "index.js"]
