# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Set environment variables for MongoDB root username and password
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=rootpassword

# Expose MongoDB port
EXPOSE 27017

# Define a volume for MongoDB data
VOLUME ["/data/db"]

# Set default command to start MongoDB
CMD ["mongod"]